polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # page for adding a new poll
    path('new/', views.new_poll, name='new'),
    path('blockchain/', views.blockchain_info, name='blockchain'),
]

survey_chain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

polls/models.py
import datetime
from django.conf import settings
from django.contrib.auth import get_user_model

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class VoterSelection(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    voter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __int__(self):
        return self.question
    class Meta:
        unique_together = [
            ['question', 'voter'],
        ]

polls/forms.py
from django import forms

from .models import Question, Choice

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['question_text',]

class ChoiceForm(forms.ModelForm):
	class Meta:
		model = Choice
		fields = ['choice_text',]

polls/views.py
import json
from web3 import Web3
from datetime import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.forms import formset_factory
from django.contrib.auth import get_user_model
from django.conf import settings

from .models import Question, Choice, VoterSelection
from .forms import *

# URL of Node Provider Service
url = 'https://ropsten.infura.io/v3/60ccb3c382e44f5b87d4ce6ce0306e57'
web3 = Web3(Web3.HTTPProvider(url))
#address = web3.toChecksumAddress() #address to deployed smart contract

# function based view to check Ethereum Node information
def blockchain_info(request):
    connection_status = web3.isConnected()
    current_block_num = web3.eth.blockNumber
    # wallet address from form input
    #print(request.GET)
    if request.method == None:
        pass
    elif request.method == 'POST':
        address = request.POST.get('address')
        print(address)
        wallet_balance = web3.eth.getBalance(address)
        wallet_balance = web3.fromWei(wallet_balance, "ether") # convert to ether
    
        tmpl_vars = {
            'connection_status': connection_status,
            'current_block_num': current_block_num,
            'wallet_balance': wallet_balance,
            'address': address,
        }
        return render(request, 'polls/blockchain.html', tmpl_vars)
    tmpl_vars = {
            'connection_status': connection_status,
            'current_block_num': current_block_num,
        }
    return render(request, 'polls/blockchain.html', tmpl_vars)

class IndexView(generic.ListView):
    
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        """Return the last five published questions
           (not including those set to be published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    
class DetailView(generic.DetailView):
    
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
    
class ResultsView(generic.DetailView):
    
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    user = request.user
    
    if request.user.is_anonymous:
        return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "Please login or signup to vote.",
        })
    else:
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        # check if the user voted on the question
        if VoterSelection.objects.filter(voter=user, question_id=question_id).exists():
            for choice in question.choice_set.all():
                return render(request, 'polls/detail.html', {
                    'question': question,
                    'error_message': "You already voted on this question.\
                                    Please vote on a dfferent question.",
                })
        
        else:
            VoterSelection.objects.create(choice=selected_choice, voter=user, question_id=question_id)
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
            
def new_poll(request):
    
    ChoiceFormSet = formset_factory(ChoiceForm, extra=3, min_num=2, validate_min=True)
    question_form = QuestionForm() # when a url is called initially it is GET method so you have to send a instance of form first (empty form)
    choice_form = ChoiceForm()
    
    if request.method == 'POST':
        form = QuestionForm(request.POST or None)
        formset = ChoiceFormSet(request.POST or None, request.FILES)
        if form.is_valid() and formset.is_valid():
            new_poll = form.save(commit=False)
            new_poll.author = request.user
            new_poll.save()
            for inline_form in formset:
                if inline_form.cleaned_data:
                    choice = inline_form.save(commit=False)
                    choice.question = new_poll
                    choice.save()
            return redirect('/polls/')
    else:
        form = QuestionForm() # this will return the errors in your form
        formset = ChoiceFormSet()
        
    tmpl_vars = {
        'formset': formset,
        'form': form,
    }
        
    return render(request, 'polls/new.html', tmpl_vars)

polls/templates/polls/blockchain.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Question Detail</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'polls:new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
        <a href="{% url 'home' %}" class="top-menu"><span class="glyphicon glyphicon-home"></span></a>
        <h1>Ethereum</h1>
    </div>
    <div class="content">
	<div class="blockchain">
	    <p>Connected to node? {{ connection_status }}</p>
	    <p>Current block number (Ropsten Network): {{ current_block_num }}</p>
	    <br>
	    <div class="wallet amount">
		<form method="POST">
		    {% csrf_token %}
		    <label for="wallet address">Enter the wallet address:</label>
		    <input type="text" id="wallet address" name="address" placeholder="0x..." size="45">
		    <input type="submit" value="Submit">
		</form>
		<br>
		<p>You entered the wallet address of: {{ address }}</p>
		<p>The amount of ETH in this wallet is: {{ wallet_balance }} </p>
	    </div>
	</div>
    </div>
  </body>
</html>

polls/templates/polls/detail.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Question Detail</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'polls:new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
        <a href="{% url 'home' %}" class="top-menu"><span class="glyphicon glyphicon-home"></span></a>
        <h1><a href="{% url 'polls:index' %}">Details</a></h1>
    </div>
    <div class="content">
    <h1>{{ question.question_text }}</h1>
    
    {% if error_message %}<p><strong>{{ error_message }}
    </strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}"
      value="{{ choice.id }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="vote">
    </form>
    </div>
  </body>
</html>

polls/templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Polls Homepage</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href="{% static 'polls/all.min.css' %}" type="text/css" rel="stylesheet">
  </head>
  <body>
    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'polls:new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
        <a href="{% url 'home' %}" class="top-menu"><span class="glyphicon glyphicon-home"></span></a>
        <a href="{% url 'polls:blockchain' %}" class="top-menu"><span class=""><i class="fab fa-ethereum" style='font-size:50px;color:black'></i></span></a>
        <h1><a href="{% url 'polls:index' %}">Question List</a></h1>
    </div>
    <div>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <h4><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a> -- Created By {{ question.author|title }}</h4>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
  </body>
</html>

polls/templates/polls/new.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Polls Homepage</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'polls:new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
        <a href="{% url 'home' %}" class="top-menu"><span class="glyphicon glyphicon-home"></span></a>
        <h1><a href="{% url 'polls:index' %}">Question List</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
<h2>Add a new question:</h2>
<form method="post" class="poll-form">
  <table>
  {% csrf_token %}
  {{ formset.management_form }}
  {{ form.as_p }}
  {{ formset.as_p }}
  </table>
  <button type="submit" class="save btn btn-default">add question</button>
</form>
            </div>
        </div>
    </div>
  </body>
</html>

polls/templates/polls/results.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Vote Results</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'polls:new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
        <a href="{% url 'home' %}" class="top-menu"><span class="glyphicon glyphicon-home"></span></a>
    <h1><a href="{% url 'polls:index' %}">Choices</a></h1>
    </div>
    <div class="content">
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
      <p>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p>
    {% endfor %}
    </ul>

    <button><a href="{% url 'polls:index' %}">Vote again?</a></button>
    </div>
  </body>
</html>