polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # page for adding a new poll
    path('new/', views.new_poll, name='new'),
    path('blockchain/', views.blockchain_info, name='blockchain'),
]

survey_chain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="page-header">
  <h1>Survey-Chain</h1>
</div>
<div class="content">
<div class="auth">
  {% if user.is_authenticated %}
    <h2>Hi {{ user.username }}!</h2>
    <button type="submit"><a href="{% url 'logout' %}" class="top-menu">Log Out</a></button>
  <header>
  {% endif %}
</div>
<div class="app-links">
  <h4><a style="font-size: 28pt; "href="{% url 'polls:index' %}">Polls</a></h4>
</div>
<div class="home-message">
  <p>Please login or signup to access all website features.</p>
  <br>
  <p>Please login or signup to access all website features.</p>
  <p>For the moment, you may even sign up with a fake email address to test the sites functionality.</p>
</div>
<div class="login-logout-buttons">
    <button type="submit"><a href="{% url 'login' %}">Log In</a></button> |
    <button type="submit"><a href="{% url 'users:signup' %}">Sign Up</a></button>
</div>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}